networks:
  default:
    name: ${DOCKER_NETWORK:-dev-op}

services:
  l1-geth-remove-db:
    image: "alpine:3.19.0"
    container_name: l1-geth-remove-db
    command: rm -rf /execution/geth
    volumes:
      - ./l1-geth/execution:/execution

  l1-beacon-remove-db:
    image: "alpine:3.19.0"
    container_name: l1-beacon-remove-db
    command: rm -rf /consensus/beacondata /consensus/validatordata /consensus/genesis.ssz
    volumes:
      - ./l1-geth/consensus:/consensus

  l1-create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:v7.1.2" # upgrade to v7.1.2 to support osakaTime
    container_name: l1-create-beacon-chain-genesis
    command:
      - testnet
      - generate-genesis
      - --fork=fulu
      - --num-validators=4
      - --genesis-time-delay=0
      - --output-ssz=/consensus/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --geth-genesis-json-in=/execution/genesis-raw.json
      - --geth-genesis-json-out=/execution/genesis.json
    volumes:
      - ./l1-geth/consensus:/consensus
      - ./l1-geth/execution:/execution
    depends_on:
      l1-beacon-remove-db:
        condition: service_completed_successfully

  l1-add-bpo-config:
    image: "alpine-jq:local"
    container_name: l1-add-bpo-config
    command:
      - /bin/sh
      - -c
      - /scripts/add-bpo-config.sh
    volumes:
      - ./l1-geth/execution:/execution
      - ./scripts:/scripts
    depends_on:
      l1-create-beacon-chain-genesis:
        condition: service_completed_successfully

  l1-geth-genesis:
    image: "ethereum/client-go:v1.16.7"
    container_name: l1-geth-genesis
    command: --datadir=/execution --gcmode=archive init --state.scheme=hash /execution/genesis.json
    volumes:
      - ./l1-geth/execution:/execution
      - ./l1-geth/execution/genesis.json:/execution/genesis.json
    depends_on:
      l1-add-bpo-config:
        condition: service_completed_successfully
      l1-geth-remove-db:
        condition: service_completed_successfully

  l1-geth:
    image: "ethereum/client-go:v1.16.7"
    container_name: l1-geth
    command:
      - --http
      - --http.api=eth,net,web3,debug,admin,txpool
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.api=eth,net,web3,debug,txpool
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/execution/jwtsecret
      - --datadir=/execution
      - --nodiscover
      - --syncmode=full
      - --gcmode=archive
      - --ipcdisable
      - --rpc.allow-unprotected-txs
      - --verbosity=3
      - --miner.gasprice=1
      - --txpool.pricelimit=0
      - --txpool.pricebump=10
      - --txpool.accountslots=100000
      - --txpool.globalslots=100000
      - --txpool.accountqueue=100000
      - --txpool.globalqueue=100000
      - --miner.gaslimit=100000000
    ports:
      - 8551:8551
      - 8545:8545
      - 8546:8546
    depends_on:
      l1-geth-genesis:
        condition: service_completed_successfully
    volumes:
      - ./l1-geth/execution:/execution
      - ./l1-geth/execution/jwtsecret:/execution/jwtsecret
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

  l1-beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:v7.0.0" # seems not work with v7.1.2, so keeps v7.0.0
    container_name: l1-beacon-chain
    command:
      - --datadir=/consensus/beacondata
      - --min-sync-peers=0
      - --genesis-state=/consensus/genesis.ssz
      - --bootstrap-node=
      - --interop-eth1data-votes
      - --chain-config-file=/consensus/config.yml
      - --contract-deployment-block=0
      - --chain-id=1337
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://l1-geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --minimum-peers-per-subnet=0
      - --blob-retention-epochs=75600
      - --verbosity=info
    depends_on:
      l1-create-beacon-chain-genesis:
        condition: service_completed_successfully
      l1-geth:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
      - 18080:8080
      - 6060:6060
      - 19090:9090
    volumes:
      - ./l1-geth/consensus:/consensus
      - ./l1-geth/execution:/execution
      - ./l1-geth/execution/jwtsecret:/execution/jwtsecret

  l1-validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:v7.0.0"
    container_name: l1-validator
    command:
      - --beacon-rpc-provider=l1-beacon-chain:4000
      - --datadir=/consensus/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=4
      - --interop-start-index=0
      - --chain-config-file=/consensus/config.yml
      - --verbosity=info
    depends_on:
      l1-beacon-chain:
        condition: service_started
    volumes:
      - ./l1-geth/consensus:/consensus

  op-batcher:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: op-batcher
    command:
      - /app/op-batcher/bin/op-batcher
      - --log.level=debug
      - --l2-eth-rpc=${OP_BATCHER_L2_ETH_RPC:-http://op-${SEQ_TYPE}-seq:8545}
      - --rollup-rpc=${OP_BATCHER_ROLLUP_RPC:-http://op-seq:9545}
      - --private-key=${OP_BATCHER_PRIVATE_KEY}
      - --poll-interval=1s
      - --batch-type=1
      - --compression-algo=brotli-10
      - --data-availability-type=blobs
      - --sub-safety-margin=6
      - --num-confirmations=4
      - --safe-abort-nonce-too-low-count=3
      - --resubmission-timeout=30s
      - --rpc.addr=0.0.0.0
      - --rpc.port=8548
      - --rpc.enable-admin
      - --max-channel-duration=150
      - --l1-eth-rpc=${L1_RPC_URL_IN_DOCKER}
      - --max-pending-tx=20
      - --target-num-frames=6
      - --throttle.block-size-upper-limit=0
      - --throttle.block-size-lower-limit=0
      - --throttle.tx-size-lower-limit=0
      - --throttle.tx-size-upper-limit=0

  op-proposer:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: op-proposer
    environment:
      - DISPUTE_GAME_FACTORY_ADDRESS=${DISPUTE_GAME_FACTORY_ADDRESS}
    command:
      - /app/op-proposer/bin/op-proposer
      - --log.level=debug
      - --poll-interval=5s
      - --wait-node-sync=true
      - --num-confirmations=1
      - --safe-abort-nonce-too-low-count=3
      - --resubmission-timeout=30s
      - --rpc.port=8560
      - --rollup-rpc=http://op-seq:9545
      - --game-factory-address=${DISPUTE_GAME_FACTORY_ADDRESS}
      - --proposal-interval=300s
      - --private-key=${OP_PROPOSER_PRIVATE_KEY}
      - --l1-eth-rpc=${L1_RPC_URL_IN_DOCKER}
      - --game-type=${GAME_TYPE:-0}
      - --genesis-height=${FORK_BLOCK}
    depends_on:
      - op-batcher

  op-challenger:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: op-challenger
    environment:
      - L1_RPC_URL_IN_DOCKER=${L1_RPC_URL_IN_DOCKER}
      - L1_BEACON_URL_IN_DOCKER=${L1_BEACON_URL_IN_DOCKER}
      - DISPUTE_GAME_FACTORY_ADDRESS=${DISPUTE_GAME_FACTORY_ADDRESS}
    volumes:
      - ./data/cannon-data:/data
      - ./config-op/rollup.json:/rollup.json
      - ./config-op/genesis.json:/l2-genesis.json
    command:
      - /app/op-challenger/bin/op-challenger
      - --log.level=debug
      - --l1-eth-rpc=${L1_RPC_URL_IN_DOCKER}
      - --l1-beacon=${L1_BEACON_URL_IN_DOCKER}
      - --l2-eth-rpc=http://op-${SEQ_TYPE}-seq:8545
      - --rollup-rpc=http://op-seq:9545
      - --game-factory-address=${DISPUTE_GAME_FACTORY_ADDRESS}
      - --cannon-bin=/app/cannon/bin/cannon
      - --cannon-server=/data/op-program
      - --cannon-prestate=/data/prestate-mt64.bin.gz
      - --cannon-rollup-config=/rollup.json
      - --cannon-l2-genesis=/l2-genesis.json
      - --private-key=${OP_PROPOSER_PRIVATE_KEY}
      - --trace-type=cannon,permissioned
      - --datadir=/data
      - --game-window=${GAME_WINDOW}s

  op-dispute-mon:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: op-dispute-mon
    depends_on:
      - op-challenger
      - op-proposer
    command:
      - /app/op-dispute-mon/bin/op-dispute-mon
      - --l1-eth-rpc=${L1_RPC_URL_IN_DOCKER}
      - --rollup-rpc=http://op-seq:9545
      - --game-factory-address=${DISPUTE_GAME_FACTORY_ADDRESS}
      - --game-window=${GAME_WINDOW}s
      - --honest-actors=${PROPOSER_ADDRESS}

  mempool-rebroadcaster:
    image: xlayerdev/mempool-rebroadcaster
    container_name: mempool-rebroadcaster

  op-succinct-fetch-config:
    image: "${OP_SUCCINCT_IMAGE_TAG}"
    container_name: fetch-config
    volumes:
      - ./op-succinct/.env.deploy:/app/.env
      - ./op-succinct/configs:/app/configs
    command:
      - fetch-fault-dispute-game-config

  op-succinct-contracts:
    image: "${OP_SUCCINCT_CONTRACTS_IMAGE_TAG}"
    container_name: op-succinct-contracts
    volumes:
      - ./op-succinct/configs/opsuccinctfdgconfig.json:/app/contracts/opsuccinctfdgconfig.json
    env_file:
      - ./op-succinct/.env.deploy
    command:
      - forge
      - script
      - script/fp/DeployOPSuccinctLite.s.sol:DeployOPSuccinctLite
      - -vvv
      - --private-key=${DEPLOYER_PRIVATE_KEY}
      - --rpc-url=${L1_RPC_URL_IN_DOCKER}
      - --broadcast

  op-succinct-proposer:
    image: "${OP_SUCCINCT_IMAGE_TAG}"
    container_name: op-succinct-proposer
    volumes:
      - ./op-succinct/.env.proposer:/app/.env
      - ./op-succinct/configs:/app/configs
    environment:
      - RUST_LOG=info
    ports:
      - "9000:9000"
    command:
      - proposer
      - --env-file=/app/.env

  op-succinct-challenger:
    image: "${OP_SUCCINCT_IMAGE_TAG}"
    container_name: op-succinct-challenger
    volumes:
      - ./op-succinct/.env.challenger:/app/.env
    ports:
      - "9001:9001"
    command:
      - challenger
      - --env-file=/app/.env

  kailua-contracts:
    image: ${KAILUA_IMAGE_TAG}
    container_name: kailua-contracts
    environment:
      - RUST_LOG="kailua=info,alloy=warn,hyper=warn,warn"
    env_file:
      - ./kailua/.env.deploy
    command:
      - kailua-cli
      - fast-track

  kailua-proposer:
    image: ${KAILUA_IMAGE_TAG}
    container_name: kailua-proposer
    env_file:
      - ./kailua/.env.proposer
    environment:
      - RUST_LOG=warn,kailua=info,kailua_proposer=info,hyper=off,hyper_util=off,alloy=warn
    volumes:
      - ./data/kailua-proposer:/data
    command:
      - kailua-cli
      - propose
      - --data-dir=/data

  kailua-validator:
    image: ${KAILUA_IMAGE_TAG}
    container_name: kailua-validator
    env_file:
      - ./kailua/.env.validator
    environment:
      - RUST_LOG=warn,kailua=info,kailua_validator=info,kailua_prover=info,kailua_sync=info,oracle_server=off,oracle_client=off,host_backend=off,risc0_zkvm=off,risc0=off,alloy=warn,alloy_rpc_client=off,alloy_json_rpc=off,alloy_transport_http=off,hyper=off,hyper_util=off,reqwest=off,kona=warn,kona_derive=warn,kona_executor=warn,kona_mpt=warn,batch_validator=warn,hint_writer=off,hint_reader=off,frame_queue=warn,channel_reader=warn,pipeline=warn
    volumes:
      - ./data/kailua-validator:/data
    command:
      - kailua-cli
      - validate
      - --data-dir=/data

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
